In [32]:
from keras.datasets import mnist

In [33]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [34]:
train_images.shape

(60000, 28, 28)

In [35]:
len(train_labels)

60000

In [36]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [37]:
len(test_labels)

10000

In [38]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [39]:
train_images[0]
#28x28

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [40]:
from keras import models
from keras import layers

#モデル定義
network = models.Sequential()
#input layer
network.add(layers.Dense(512, activation='relu', input_shape=(28*28, )))
#output layer
#0-9の10種類他クラス分類
network.add(layers.Dense(10, activation='softmax'))

In [41]:
#モデルのコンパイル
network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

In [42]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0,1))

#データのスケーリング

#次元変換
train_images = train_images.reshape((60000, 28*28))
#型変換
train_images = train_images.astype('float32')
#0-1で正規化
scaler.fit(train_images)
train_images = scaler.fit_transform(train_images)

#次元変換
test_images = test_images.reshape((10000, 28*28))
#型変換
test_images = test_images.astype('float32')
#0-1で正規化
scaler.fit(test_images)
test_images = scaler.fit_transform(test_images)


In [43]:
#ラベルのカテゴリー化
from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [44]:
train_labels[:3]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)

In [45]:
#ミニバッチ勾配降下法による学習
#ミニバッチサイズ = 128
#エポック数 = 5
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Epoch 1/5
60000/60000 [==============================] - 10s 160us/step - loss: 0.2542 - acc: 0.9265
Epoch 2/5
60000/60000 [==============================] - 11s 181us/step - loss: 0.1045 - acc: 0.9687
Epoch 3/5
60000/60000 [==============================] - 10s 163us/step - loss: 0.0694 - acc: 0.9791
Epoch 4/5
60000/60000 [==============================] - 10s 169us/step - loss: 0.0496 - acc: 0.9849
Epoch 5/5
60000/60000 [==============================] - 10s 163us/step - loss: 0.0380 - acc: 0.9886


In [46]:
#テストデータで評価
test_loss, test_acc = network.evaluate(test_images, test_labels)

10000/10000 [==============================] - 2s 158us/step


In [47]:
#正解率
print('test_acc:', test_acc)

test_acc: 0.9794
